name: Generate a build and push to another branch

on:
  push:
    branches:
      - master # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Building a branch
        run: git checkout --orphan build

      - name: Clear this branch make it empty for prodution
        run: git rm -rf .

      - name: Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout --orphan build
          git --work-tree=build add --all
          git --work-tree=build commit -m "Production build"
          git push origin HEAD:build --force
